# file name
name: main
on: 
  push:
    branches: [main]
    
jobs:
  Build:
    name: Build hexlet-ci-app on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.1.7
      - uses: actions/setup-node@v4.0.3
      - name: Start serup
        run: make setup
      - name: Start test
        run: make test
      - name: Start linter  
        run: make lint
      
